# Generated by Django 4.0 on 2022-09-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_links', '0002_remove_link_active_link_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
