# Generated by Django 4.0 on 2022-09-02 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('short_links', '0003_link_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='long_link',
        ),
    ]
