# Generated by Django 4.0 on 2022-08-30 18:50

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0002_notificationlog_stages_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationlog',
            name='type',
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('like', 'like'), ('mass_mail', 'mass_mail'), ('welcome', 'welcome')], default='', max_length=20, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='stage',
            field=models.CharField(blank=True, choices=[('new', 'new'), ('failed', 'failed'), ('success', 'success')], default='new', max_length=20, verbose_name='type'),
        ),
    ]
