# Generated by Django 4.0 on 2022-08-31 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0003_remove_notificationlog_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='send_tries',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('like', 'like'), ('mass_mail', 'mass_mail'), ('welcome', 'welcome')], default='', max_length=20, verbose_name='notification_type'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='stage',
            field=models.CharField(blank=True, choices=[('new', 'new'), ('failed', 'failed'), ('success', 'success')], default='new', max_length=20, verbose_name='Stage'),
        ),
    ]
