# Generated by Django 4.0 on 2022-09-04 18:20

import uuid

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0004_notificationlog_send_tries_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_age', models.SmallIntegerField(blank=True, default=6, help_text='Укажите минимальный возраст получателей.<br> Примечание:<br> &emsp; - Возраст может быть не меньше 6 лет.<br> &emsp; - Поле может быть пустым.<br> &emsp; - По умолчанию 6 лет.', validators=[django.core.validators.MinValueValidator(6)], verbose_name='Минимальный возраст.')),
                ('to_age', models.SmallIntegerField(blank=True, default=125, help_text='Укажите максимальный возраст получателей.<br> Примечание:<br> &emsp; -  Поле может быть пустым.<br> &emsp; -  По умолчанию 125 лет.', validators=[django.core.validators.MinValueValidator(7)], verbose_name='Максимальный возраст.')),
                ('sex', models.CharField(blank=True, choices=[('M', ' Мужчины'), ('F', 'Женщины'), ('FM', 'Всем')], default='FM', help_text='Выбрать пол получателей, по умолчанию отправка будет производится всем.', max_length=2, verbose_name='Пол получателей.')),
                ('subject', models.CharField(help_text='Максимальная длина - 125 символов.', max_length=125, verbose_name='Тема письма.')),
                ('title', models.CharField(help_text='Максимальная длина - 125 символов.', max_length=125, verbose_name='Заглавие.')),
                ('message', models.TextField(verbose_name='Текст сообщения.')),
                ('sent', models.BooleanField(default=False, verbose_name='Отправлено.')),
                ('error', models.CharField(blank=True, max_length=255, verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания.')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления.')),
            ],
            options={
                'verbose_name': 'Поручение',
                'verbose_name_plural': 'Поручения',
            },
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('like', 'like'), ('mass_mail', 'mass_mail'), ('welcome', 'welcome'), ('new_movie', 'new_movie'), ('assignment', 'assignment')], default='', max_length=20, verbose_name='notification_type'),
        ),
    ]
