# Generated by Django 2.2 on 2020-07-29 12:00

from django.db import migrations


def create_task(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    IntervalSchedule = apps.get_model('django_celery_beat', 'intervalschedule')
    interval_1_min, _ = IntervalSchedule.objects.using(db_alias).get_or_create(**{
        'every': 1,
        'period': 'minutes'
    })

    PeriodicTask = apps.get_model('django_celery_beat', 'periodictask')
    PeriodicTask.objects.using(db_alias).update_or_create(
        task='notify.tasks.task_discover_new',
        defaults=dict(
            name='Discover new notifications every 1 minute',
            interval_id=interval_1_min.id,
            args='[]',
            enabled=True
        )
    )


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(create_task, reverse_code=migrations.RunPython.noop),
    ]
